# Generated by Django 3.0.2 on 2020-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(null=True),
        ),
    ]
