# Generated by Django 3.0.2 on 2020-01-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('related_object_sample', '0002_auto_20200119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='related_object_sample.Reporter'),
        ),
    ]
